### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by xnil** [turnage/graw#6]
There should be a documented guideline for contributions for external contributors. It should outline:

- Coding conventions
- File/folder naming conventions
- Project structure
- Git conventions
- Testing conventions/requirements
- Anything else that would benefit from being specified and standardized for newcomers and currently existing contributors alike

At first, a CONTRIBUTING.md would certainly suffice in laying out the ground principles for contribution.

**Comment by turnage** [comment]
I see you've started a commit for this. If you want to continue, I've outlined what I'm thinking below. Otherwise I can return and add this later.

Coding conventions: I think compliance with [Effective Go](https://golang.org/doc/effective_go.html) is sufficient.

Testing conventions/requirements: All commits must pass all tests; new behavior requires new tests to verify new behavior. [Short link on tests](https://golang.org/doc/code.html#Testing). Remember to run ````go test ./...```` from the root directory.

Contributions: are neat! Contributions should start as an issue first if they change the behavior of any package (even internal). Contributions are accepted through PRs.
